<?php
/**
 * FixturesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API-FOOTBALL
 *
 * +830 football leagues & cups. Livescore (15s), odds, events, line-ups, coachs, players, top scorers, standings, statistics, transfers, predictions. Documentation : https://www.api-football.com/documentation-v3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FootballApi\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use FootballApi\Client\ApiException;
use FootballApi\Client\Configuration;
use FootballApi\Client\HeaderSelector;
use FootballApi\Client\ObjectSerializer;

/**
 * FixturesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FixturesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client,
        Configuration $config,
        HeaderSelector $selector
    ) {
        $this->client = $client;
        $this->config = $config;
        $this->headerSelector = $selector;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v3FixturesHeadToHeadBetweenTwoTeams
     *
     * @param  string $h2h The ids of the teams &#x60;id-id&#x60; (required)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $from A valid date (optional)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3FixturesHeadToHeadBetweenTwoTeams($h2h, $status = null, $to = null, $date = null, $from = null, $last = null, $timezone = null, $league = null, $season = null, $next = null)
    {
        $this->v3FixturesHeadToHeadBetweenTwoTeamsWithHttpInfo($h2h, $status, $to, $date, $from, $last, $timezone, $league, $season, $next);
    }

    /**
     * Operation v3FixturesHeadToHeadBetweenTwoTeamsWithHttpInfo
     *
     * @param  string $h2h The ids of the teams &#x60;id-id&#x60; (required)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $from A valid date (optional)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3FixturesHeadToHeadBetweenTwoTeamsWithHttpInfo($h2h, $status = null, $to = null, $date = null, $from = null, $last = null, $timezone = null, $league = null, $season = null, $next = null)
    {
        $returnType = '';
        $request = $this->v3FixturesHeadToHeadBetweenTwoTeamsRequest($h2h, $status, $to, $date, $from, $last, $timezone, $league, $season, $next);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3FixturesHeadToHeadBetweenTwoTeamsAsync
     *
     * 
     *
     * @param  string $h2h The ids of the teams &#x60;id-id&#x60; (required)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $from A valid date (optional)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3FixturesHeadToHeadBetweenTwoTeamsAsync($h2h, $status = null, $to = null, $date = null, $from = null, $last = null, $timezone = null, $league = null, $season = null, $next = null)
    {
        return $this->v3FixturesHeadToHeadBetweenTwoTeamsAsyncWithHttpInfo($h2h, $status, $to, $date, $from, $last, $timezone, $league, $season, $next)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3FixturesHeadToHeadBetweenTwoTeamsAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $h2h The ids of the teams &#x60;id-id&#x60; (required)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $from A valid date (optional)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3FixturesHeadToHeadBetweenTwoTeamsAsyncWithHttpInfo($h2h, $status = null, $to = null, $date = null, $from = null, $last = null, $timezone = null, $league = null, $season = null, $next = null)
    {
        $returnType = '';
        $request = $this->v3FixturesHeadToHeadBetweenTwoTeamsRequest($h2h, $status, $to, $date, $from, $last, $timezone, $league, $season, $next);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3FixturesHeadToHeadBetweenTwoTeams'
     *
     * @param  string $h2h The ids of the teams &#x60;id-id&#x60; (required)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $from A valid date (optional)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3FixturesHeadToHeadBetweenTwoTeamsRequest($h2h, $status = null, $to = null, $date = null, $from = null, $last = null, $timezone = null, $league = null, $season = null, $next = null)
    {
        // verify the required parameter 'h2h' is set
        if ($h2h === null || (is_array($h2h) && count($h2h) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $h2h when calling v3FixturesHeadToHeadBetweenTwoTeams'
            );
        }

        $resourcePath = '/v3/fixtures/headtohead';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status, null);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to, null);
        }
        // query params
        if ($date !== null) {
            $queryParams['date'] = ObjectSerializer::toQueryValue($date, null);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from, null);
        }
        // query params
        if ($last !== null) {
            $queryParams['last'] = ObjectSerializer::toQueryValue($last, null);
        }
        // query params
        if ($timezone !== null) {
            $queryParams['timezone'] = ObjectSerializer::toQueryValue($timezone, null);
        }
        // query params
        if ($league !== null) {
            $queryParams['league'] = ObjectSerializer::toQueryValue($league, null);
        }
        // query params
        if ($season !== null) {
            $queryParams['season'] = ObjectSerializer::toQueryValue($season, null);
        }
        // query params
        if ($next !== null) {
            $queryParams['next'] = ObjectSerializer::toQueryValue($next, null);
        }
        // query params
        if ($h2h !== null) {
            $queryParams['h2h'] = ObjectSerializer::toQueryValue($h2h, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3FixturesInProgressLiveScore
     *
     * @param  float $league The id of the league (optional)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the fixture (optional)
     * @param  string $round The round of the fixture (optional)
     * @param  string $live Enum: &#x60;all&#x60; or &#x60;id-id&#x60; for filter by league id (optional, default to all)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $from A valid date (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3FixturesInProgressLiveScore($league = null, $status = null, $team = null, $id = null, $round = null, $live = 'all', $last = null, $from = null, $season = null, $next = null, $to = null, $date = null, $timezone = null)
    {
        $this->v3FixturesInProgressLiveScoreWithHttpInfo($league, $status, $team, $id, $round, $live, $last, $from, $season, $next, $to, $date, $timezone);
    }

    /**
     * Operation v3FixturesInProgressLiveScoreWithHttpInfo
     *
     * @param  float $league The id of the league (optional)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the fixture (optional)
     * @param  string $round The round of the fixture (optional)
     * @param  string $live Enum: &#x60;all&#x60; or &#x60;id-id&#x60; for filter by league id (optional, default to all)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $from A valid date (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3FixturesInProgressLiveScoreWithHttpInfo($league = null, $status = null, $team = null, $id = null, $round = null, $live = 'all', $last = null, $from = null, $season = null, $next = null, $to = null, $date = null, $timezone = null)
    {
        $returnType = '';
        $request = $this->v3FixturesInProgressLiveScoreRequest($league, $status, $team, $id, $round, $live, $last, $from, $season, $next, $to, $date, $timezone);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3FixturesInProgressLiveScoreAsync
     *
     * 
     *
     * @param  float $league The id of the league (optional)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the fixture (optional)
     * @param  string $round The round of the fixture (optional)
     * @param  string $live Enum: &#x60;all&#x60; or &#x60;id-id&#x60; for filter by league id (optional, default to all)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $from A valid date (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3FixturesInProgressLiveScoreAsync($league = null, $status = null, $team = null, $id = null, $round = null, $live = 'all', $last = null, $from = null, $season = null, $next = null, $to = null, $date = null, $timezone = null)
    {
        return $this->v3FixturesInProgressLiveScoreAsyncWithHttpInfo($league, $status, $team, $id, $round, $live, $last, $from, $season, $next, $to, $date, $timezone)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3FixturesInProgressLiveScoreAsyncWithHttpInfo
     *
     * 
     *
     * @param  float $league The id of the league (optional)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the fixture (optional)
     * @param  string $round The round of the fixture (optional)
     * @param  string $live Enum: &#x60;all&#x60; or &#x60;id-id&#x60; for filter by league id (optional, default to all)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $from A valid date (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3FixturesInProgressLiveScoreAsyncWithHttpInfo($league = null, $status = null, $team = null, $id = null, $round = null, $live = 'all', $last = null, $from = null, $season = null, $next = null, $to = null, $date = null, $timezone = null)
    {
        $returnType = '';
        $request = $this->v3FixturesInProgressLiveScoreRequest($league, $status, $team, $id, $round, $live, $last, $from, $season, $next, $to, $date, $timezone);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3FixturesInProgressLiveScore'
     *
     * @param  float $league The id of the league (optional)
     * @param  string $status The &#x60;status short&#x60; of the fixture Like NS, FT ... (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the fixture (optional)
     * @param  string $round The round of the fixture (optional)
     * @param  string $live Enum: &#x60;all&#x60; or &#x60;id-id&#x60; for filter by league id (optional, default to all)
     * @param  float $last For the X last fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $from A valid date (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020; 2021 ... (optional)
     * @param  float $next For the X next fixtures &#x60;&lt;&#x3D; 2 characters&#x60; (optional)
     * @param  string $to A valid date (optional)
     * @param  string $date A valid date (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3FixturesInProgressLiveScoreRequest($league = null, $status = null, $team = null, $id = null, $round = null, $live = 'all', $last = null, $from = null, $season = null, $next = null, $to = null, $date = null, $timezone = null)
    {

        $resourcePath = '/v3/fixtures';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($league !== null) {
            $queryParams['league'] = ObjectSerializer::toQueryValue($league, null);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status, null);
        }
        // query params
        if ($team !== null) {
            $queryParams['team'] = ObjectSerializer::toQueryValue($team, null);
        }
        // query params
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id, null);
        }
        // query params
        if ($round !== null) {
            $queryParams['round'] = ObjectSerializer::toQueryValue($round, null);
        }
        // query params
        if ($live !== null) {
            $queryParams['live'] = ObjectSerializer::toQueryValue($live, null);
        }
        // query params
        if ($last !== null) {
            $queryParams['last'] = ObjectSerializer::toQueryValue($last, null);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from, null);
        }
        // query params
        if ($season !== null) {
            $queryParams['season'] = ObjectSerializer::toQueryValue($season, null);
        }
        // query params
        if ($next !== null) {
            $queryParams['next'] = ObjectSerializer::toQueryValue($next, null);
        }
        // query params
        if ($to !== null) {
            $queryParams['to'] = ObjectSerializer::toQueryValue($to, null);
        }
        // query params
        if ($date !== null) {
            $queryParams['date'] = ObjectSerializer::toQueryValue($date, null);
        }
        // query params
        if ($timezone !== null) {
            $queryParams['timezone'] = ObjectSerializer::toQueryValue($timezone, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3FixturesRounds
     *
     * @param  float $league The id of the league (required)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020, 2021 ... (required)
     * @param  string $current Retrun the current round only  Enum: &#x60;true&#x60; or &#x60;false&#x60; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3FixturesRounds($league, $season, $current = null)
    {
        $this->v3FixturesRoundsWithHttpInfo($league, $season, $current);
    }

    /**
     * Operation v3FixturesRoundsWithHttpInfo
     *
     * @param  float $league The id of the league (required)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020, 2021 ... (required)
     * @param  string $current Retrun the current round only  Enum: &#x60;true&#x60; or &#x60;false&#x60; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3FixturesRoundsWithHttpInfo($league, $season, $current = null)
    {
        $returnType = '';
        $request = $this->v3FixturesRoundsRequest($league, $season, $current);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3FixturesRoundsAsync
     *
     * 
     *
     * @param  float $league The id of the league (required)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020, 2021 ... (required)
     * @param  string $current Retrun the current round only  Enum: &#x60;true&#x60; or &#x60;false&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3FixturesRoundsAsync($league, $season, $current = null)
    {
        return $this->v3FixturesRoundsAsyncWithHttpInfo($league, $season, $current)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3FixturesRoundsAsyncWithHttpInfo
     *
     * 
     *
     * @param  float $league The id of the league (required)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020, 2021 ... (required)
     * @param  string $current Retrun the current round only  Enum: &#x60;true&#x60; or &#x60;false&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3FixturesRoundsAsyncWithHttpInfo($league, $season, $current = null)
    {
        $returnType = '';
        $request = $this->v3FixturesRoundsRequest($league, $season, $current);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3FixturesRounds'
     *
     * @param  float $league The id of the league (required)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2020, 2021 ... (required)
     * @param  string $current Retrun the current round only  Enum: &#x60;true&#x60; or &#x60;false&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3FixturesRoundsRequest($league, $season, $current = null)
    {
        // verify the required parameter 'league' is set
        if ($league === null || (is_array($league) && count($league) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $league when calling v3FixturesRounds'
            );
        }
        // verify the required parameter 'season' is set
        if ($season === null || (is_array($season) && count($season) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $season when calling v3FixturesRounds'
            );
        }

        $resourcePath = '/v3/fixtures/rounds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($current !== null) {
            $queryParams['current'] = ObjectSerializer::toQueryValue($current, null);
        }
        // query params
        if ($league !== null) {
            $queryParams['league'] = ObjectSerializer::toQueryValue($league, null);
        }
        // query params
        if ($season !== null) {
            $queryParams['season'] = ObjectSerializer::toQueryValue($season, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
