<?php
/**
 * InjuriesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API-FOOTBALL
 *
 * +830 football leagues & cups. Livescore (15s), odds, events, line-ups, coachs, players, top scorers, standings, statistics, transfers, predictions. Documentation : https://www.api-football.com/documentation-v3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FootballApi\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use FootballApi\Client\ApiException;
use FootballApi\Client\Configuration;
use FootballApi\Client\HeaderSelector;
use FootballApi\Client\ObjectSerializer;

/**
 * InjuriesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InjuriesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client,
        Configuration $config,
        HeaderSelector $selector
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v3InjuriesByLeagueIdAndSeason
     *
     * @param  float $team The id of the team (optional)
     * @param  float $player The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $fixture The id of the fixture (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  string $date A valid date (optional)
     * @param  float $season The season of the league, **required** with &#x60;league&#x60;, &#x60;team&#x60; and &#x60;player&#x60; parameters (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3InjuriesByLeagueIdAndSeason($team = null, $player = null, $league = null, $fixture = null, $timezone = null, $date = null, $season = null)
    {
        $this->v3InjuriesByLeagueIdAndSeasonWithHttpInfo($team, $player, $league, $fixture, $timezone, $date, $season);
    }

    /**
     * Operation v3InjuriesByLeagueIdAndSeasonWithHttpInfo
     *
     * @param  float $team The id of the team (optional)
     * @param  float $player The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $fixture The id of the fixture (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  string $date A valid date (optional)
     * @param  float $season The season of the league, **required** with &#x60;league&#x60;, &#x60;team&#x60; and &#x60;player&#x60; parameters (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3InjuriesByLeagueIdAndSeasonWithHttpInfo($team = null, $player = null, $league = null, $fixture = null, $timezone = null, $date = null, $season = null)
    {
        $returnType = '';
        $request = $this->v3InjuriesByLeagueIdAndSeasonRequest($team, $player, $league, $fixture, $timezone, $date, $season);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3InjuriesByLeagueIdAndSeasonAsync
     *
     * 
     *
     * @param  float $team The id of the team (optional)
     * @param  float $player The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $fixture The id of the fixture (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  string $date A valid date (optional)
     * @param  float $season The season of the league, **required** with &#x60;league&#x60;, &#x60;team&#x60; and &#x60;player&#x60; parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3InjuriesByLeagueIdAndSeasonAsync($team = null, $player = null, $league = null, $fixture = null, $timezone = null, $date = null, $season = null)
    {
        return $this->v3InjuriesByLeagueIdAndSeasonAsyncWithHttpInfo($team, $player, $league, $fixture, $timezone, $date, $season)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3InjuriesByLeagueIdAndSeasonAsyncWithHttpInfo
     *
     * 
     *
     * @param  float $team The id of the team (optional)
     * @param  float $player The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $fixture The id of the fixture (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  string $date A valid date (optional)
     * @param  float $season The season of the league, **required** with &#x60;league&#x60;, &#x60;team&#x60; and &#x60;player&#x60; parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3InjuriesByLeagueIdAndSeasonAsyncWithHttpInfo($team = null, $player = null, $league = null, $fixture = null, $timezone = null, $date = null, $season = null)
    {
        $returnType = '';
        $request = $this->v3InjuriesByLeagueIdAndSeasonRequest($team, $player, $league, $fixture, $timezone, $date, $season);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3InjuriesByLeagueIdAndSeason'
     *
     * @param  float $team The id of the team (optional)
     * @param  float $player The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $fixture The id of the fixture (optional)
     * @param  string $timezone A valid timezone from the endpoint &#x60;Timezone&#x60; (optional)
     * @param  string $date A valid date (optional)
     * @param  float $season The season of the league, **required** with &#x60;league&#x60;, &#x60;team&#x60; and &#x60;player&#x60; parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3InjuriesByLeagueIdAndSeasonRequest($team = null, $player = null, $league = null, $fixture = null, $timezone = null, $date = null, $season = null)
    {

        $resourcePath = '/v3/injuries';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($team !== null) {
            $queryParams['team'] = ObjectSerializer::toQueryValue($team, null);
        }
        // query params
        if ($player !== null) {
            $queryParams['player'] = ObjectSerializer::toQueryValue($player, null);
        }
        // query params
        if ($league !== null) {
            $queryParams['league'] = ObjectSerializer::toQueryValue($league, null);
        }
        // query params
        if ($fixture !== null) {
            $queryParams['fixture'] = ObjectSerializer::toQueryValue($fixture, null);
        }
        // query params
        if ($timezone !== null) {
            $queryParams['timezone'] = ObjectSerializer::toQueryValue($timezone, null);
        }
        // query params
        if ($date !== null) {
            $queryParams['date'] = ObjectSerializer::toQueryValue($date, null);
        }
        // query params
        if ($season !== null) {
            $queryParams['season'] = ObjectSerializer::toQueryValue($season, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
