<?php
/**
 * SearchApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API-FOOTBALL
 *
 * +830 football leagues & cups. Livescore (15s), odds, events, line-ups, coachs, players, top scorers, standings, statistics, transfers, predictions. Documentation : https://www.api-football.com/documentation-v3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FootballApi\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use FootballApi\Client\ApiException;
use FootballApi\Client\Configuration;
use FootballApi\Client\HeaderSelector;
use FootballApi\Client\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client,
        Configuration $config,
        HeaderSelector $selector
    ) {
        $this->client = $client;
        $this->config = $config;
        $this->headerSelector = $selector;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v3SearchBet
     *
     * @param  string $search The name of the bet (optional, default to winner)
     * @param  float $id The id of the bet (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3SearchBet($search = 'winner', $id = null)
    {
        $this->v3SearchBetWithHttpInfo($search, $id);
    }

    /**
     * Operation v3SearchBetWithHttpInfo
     *
     * @param  string $search The name of the bet (optional, default to winner)
     * @param  float $id The id of the bet (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3SearchBetWithHttpInfo($search = 'winner', $id = null)
    {
        $returnType = '';
        $request = $this->v3SearchBetRequest($search, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3SearchBetAsync
     *
     * 
     *
     * @param  string $search The name of the bet (optional, default to winner)
     * @param  float $id The id of the bet (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchBetAsync($search = 'winner', $id = null)
    {
        return $this->v3SearchBetAsyncWithHttpInfo($search, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3SearchBetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $search The name of the bet (optional, default to winner)
     * @param  float $id The id of the bet (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchBetAsyncWithHttpInfo($search = 'winner', $id = null)
    {
        $returnType = '';
        $request = $this->v3SearchBetRequest($search, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3SearchBet'
     *
     * @param  string $search The name of the bet (optional, default to winner)
     * @param  float $id The id of the bet (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3SearchBetRequest($search = 'winner', $id = null)
    {

        $resourcePath = '/v3/odds/bets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }
        // query params
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3SearchBookmaker
     *
     * @param  string $search The name of the bookmaker (optional, default to bwi)
     * @param  float $id The id of the bookmaker (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3SearchBookmaker($search = 'bwi', $id = null)
    {
        $this->v3SearchBookmakerWithHttpInfo($search, $id);
    }

    /**
     * Operation v3SearchBookmakerWithHttpInfo
     *
     * @param  string $search The name of the bookmaker (optional, default to bwi)
     * @param  float $id The id of the bookmaker (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3SearchBookmakerWithHttpInfo($search = 'bwi', $id = null)
    {
        $returnType = '';
        $request = $this->v3SearchBookmakerRequest($search, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3SearchBookmakerAsync
     *
     * 
     *
     * @param  string $search The name of the bookmaker (optional, default to bwi)
     * @param  float $id The id of the bookmaker (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchBookmakerAsync($search = 'bwi', $id = null)
    {
        return $this->v3SearchBookmakerAsyncWithHttpInfo($search, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3SearchBookmakerAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $search The name of the bookmaker (optional, default to bwi)
     * @param  float $id The id of the bookmaker (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchBookmakerAsyncWithHttpInfo($search = 'bwi', $id = null)
    {
        $returnType = '';
        $request = $this->v3SearchBookmakerRequest($search, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3SearchBookmaker'
     *
     * @param  string $search The name of the bookmaker (optional, default to bwi)
     * @param  float $id The id of the bookmaker (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3SearchBookmakerRequest($search = 'bwi', $id = null)
    {

        $resourcePath = '/v3/odds/bookmakers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }
        // query params
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3SearchCoach
     *
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the coach (optional)
     * @param  string $search The name of the coach &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to tuche)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3SearchCoach($team = null, $id = null, $search = 'tuche')
    {
        $this->v3SearchCoachWithHttpInfo($team, $id, $search);
    }

    /**
     * Operation v3SearchCoachWithHttpInfo
     *
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the coach (optional)
     * @param  string $search The name of the coach &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to tuche)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3SearchCoachWithHttpInfo($team = null, $id = null, $search = 'tuche')
    {
        $returnType = '';
        $request = $this->v3SearchCoachRequest($team, $id, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3SearchCoachAsync
     *
     * 
     *
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the coach (optional)
     * @param  string $search The name of the coach &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to tuche)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchCoachAsync($team = null, $id = null, $search = 'tuche')
    {
        return $this->v3SearchCoachAsyncWithHttpInfo($team, $id, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3SearchCoachAsyncWithHttpInfo
     *
     * 
     *
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the coach (optional)
     * @param  string $search The name of the coach &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to tuche)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchCoachAsyncWithHttpInfo($team = null, $id = null, $search = 'tuche')
    {
        $returnType = '';
        $request = $this->v3SearchCoachRequest($team, $id, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3SearchCoach'
     *
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the coach (optional)
     * @param  string $search The name of the coach &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to tuche)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3SearchCoachRequest($team = null, $id = null, $search = 'tuche')
    {

        $resourcePath = '/v3/coachs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($team !== null) {
            $queryParams['team'] = ObjectSerializer::toQueryValue($team, null);
        }
        // query params
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id, null);
        }
        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3SearchCountry
     *
     * @param  string $name The name of the country (optional)
     * @param  string $code The Alpha2 code of the country &#x60;2 characters&#x60; Like  FR, GB, IT… (optional)
     * @param  string $search The name of the country &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to engl)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3SearchCountry($name = null, $code = null, $search = 'engl')
    {
        $this->v3SearchCountryWithHttpInfo($name, $code, $search);
    }

    /**
     * Operation v3SearchCountryWithHttpInfo
     *
     * @param  string $name The name of the country (optional)
     * @param  string $code The Alpha2 code of the country &#x60;2 characters&#x60; Like  FR, GB, IT… (optional)
     * @param  string $search The name of the country &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to engl)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3SearchCountryWithHttpInfo($name = null, $code = null, $search = 'engl')
    {
        $returnType = '';
        $request = $this->v3SearchCountryRequest($name, $code, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3SearchCountryAsync
     *
     * 
     *
     * @param  string $name The name of the country (optional)
     * @param  string $code The Alpha2 code of the country &#x60;2 characters&#x60; Like  FR, GB, IT… (optional)
     * @param  string $search The name of the country &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to engl)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchCountryAsync($name = null, $code = null, $search = 'engl')
    {
        return $this->v3SearchCountryAsyncWithHttpInfo($name, $code, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3SearchCountryAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $name The name of the country (optional)
     * @param  string $code The Alpha2 code of the country &#x60;2 characters&#x60; Like  FR, GB, IT… (optional)
     * @param  string $search The name of the country &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to engl)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchCountryAsyncWithHttpInfo($name = null, $code = null, $search = 'engl')
    {
        $returnType = '';
        $request = $this->v3SearchCountryRequest($name, $code, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3SearchCountry'
     *
     * @param  string $name The name of the country (optional)
     * @param  string $code The Alpha2 code of the country &#x60;2 characters&#x60; Like  FR, GB, IT… (optional)
     * @param  string $search The name of the country &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to engl)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3SearchCountryRequest($name = null, $code = null, $search = 'engl')
    {

        $resourcePath = '/v3/countries';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name, null);
        }
        // query params
        if ($code !== null) {
            $queryParams['code'] = ObjectSerializer::toQueryValue($code, null);
        }
        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3SearchPlayer
     *
     * @param  float $season The season of the league &#x60;4 characters&#x60; Requires the fields &#x60;Id&#x60;, &#x60;League&#x60; or &#x60;Team&#x60; (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $page Use for the pagination Default: &#x60;1&#x60; (optional)
     * @param  string $search The name of the player &#x60;&gt;&#x3D; 4 characters&#x60; Requires the fields &#x60;League&#x60; or &#x60;Team&#x60; (optional, default to neymar)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3SearchPlayer($season = null, $team = null, $id = null, $league = null, $page = null, $search = 'neymar')
    {
        $this->v3SearchPlayerWithHttpInfo($season, $team, $id, $league, $page, $search);
    }

    /**
     * Operation v3SearchPlayerWithHttpInfo
     *
     * @param  float $season The season of the league &#x60;4 characters&#x60; Requires the fields &#x60;Id&#x60;, &#x60;League&#x60; or &#x60;Team&#x60; (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $page Use for the pagination Default: &#x60;1&#x60; (optional)
     * @param  string $search The name of the player &#x60;&gt;&#x3D; 4 characters&#x60; Requires the fields &#x60;League&#x60; or &#x60;Team&#x60; (optional, default to neymar)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3SearchPlayerWithHttpInfo($season = null, $team = null, $id = null, $league = null, $page = null, $search = 'neymar')
    {
        $returnType = '';
        $request = $this->v3SearchPlayerRequest($season, $team, $id, $league, $page, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3SearchPlayerAsync
     *
     * 
     *
     * @param  float $season The season of the league &#x60;4 characters&#x60; Requires the fields &#x60;Id&#x60;, &#x60;League&#x60; or &#x60;Team&#x60; (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $page Use for the pagination Default: &#x60;1&#x60; (optional)
     * @param  string $search The name of the player &#x60;&gt;&#x3D; 4 characters&#x60; Requires the fields &#x60;League&#x60; or &#x60;Team&#x60; (optional, default to neymar)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchPlayerAsync($season = null, $team = null, $id = null, $league = null, $page = null, $search = 'neymar')
    {
        return $this->v3SearchPlayerAsyncWithHttpInfo($season, $team, $id, $league, $page, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3SearchPlayerAsyncWithHttpInfo
     *
     * 
     *
     * @param  float $season The season of the league &#x60;4 characters&#x60; Requires the fields &#x60;Id&#x60;, &#x60;League&#x60; or &#x60;Team&#x60; (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $page Use for the pagination Default: &#x60;1&#x60; (optional)
     * @param  string $search The name of the player &#x60;&gt;&#x3D; 4 characters&#x60; Requires the fields &#x60;League&#x60; or &#x60;Team&#x60; (optional, default to neymar)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchPlayerAsyncWithHttpInfo($season = null, $team = null, $id = null, $league = null, $page = null, $search = 'neymar')
    {
        $returnType = '';
        $request = $this->v3SearchPlayerRequest($season, $team, $id, $league, $page, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3SearchPlayer'
     *
     * @param  float $season The season of the league &#x60;4 characters&#x60; Requires the fields &#x60;Id&#x60;, &#x60;League&#x60; or &#x60;Team&#x60; (optional)
     * @param  float $team The id of the team (optional)
     * @param  float $id The id of the player (optional)
     * @param  float $league The id of the league (optional)
     * @param  float $page Use for the pagination Default: &#x60;1&#x60; (optional)
     * @param  string $search The name of the player &#x60;&gt;&#x3D; 4 characters&#x60; Requires the fields &#x60;League&#x60; or &#x60;Team&#x60; (optional, default to neymar)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3SearchPlayerRequest($season = null, $team = null, $id = null, $league = null, $page = null, $search = 'neymar')
    {

        $resourcePath = '/v3/players';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($season !== null) {
            $queryParams['season'] = ObjectSerializer::toQueryValue($season, null);
        }
        // query params
        if ($team !== null) {
            $queryParams['team'] = ObjectSerializer::toQueryValue($team, null);
        }
        // query params
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id, null);
        }
        // query params
        if ($league !== null) {
            $queryParams['league'] = ObjectSerializer::toQueryValue($league, null);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page, null);
        }
        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3SearchTeam
     *
     * @param  float $league The id of the league (optional)
     * @param  string $search The name or the country name of the team &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to manches)
     * @param  string $country The country name of the team (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2019, 2020, 2021 ... (optional)
     * @param  float $id The id of the team (optional)
     * @param  string $name The name of the team (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3SearchTeam($league = null, $search = 'manches', $country = null, $season = null, $id = null, $name = null)
    {
        $this->v3SearchTeamWithHttpInfo($league, $search, $country, $season, $id, $name);
    }

    /**
     * Operation v3SearchTeamWithHttpInfo
     *
     * @param  float $league The id of the league (optional)
     * @param  string $search The name or the country name of the team &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to manches)
     * @param  string $country The country name of the team (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2019, 2020, 2021 ... (optional)
     * @param  float $id The id of the team (optional)
     * @param  string $name The name of the team (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3SearchTeamWithHttpInfo($league = null, $search = 'manches', $country = null, $season = null, $id = null, $name = null)
    {
        $returnType = '';
        $request = $this->v3SearchTeamRequest($league, $search, $country, $season, $id, $name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3SearchTeamAsync
     *
     * 
     *
     * @param  float $league The id of the league (optional)
     * @param  string $search The name or the country name of the team &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to manches)
     * @param  string $country The country name of the team (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2019, 2020, 2021 ... (optional)
     * @param  float $id The id of the team (optional)
     * @param  string $name The name of the team (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchTeamAsync($league = null, $search = 'manches', $country = null, $season = null, $id = null, $name = null)
    {
        return $this->v3SearchTeamAsyncWithHttpInfo($league, $search, $country, $season, $id, $name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3SearchTeamAsyncWithHttpInfo
     *
     * 
     *
     * @param  float $league The id of the league (optional)
     * @param  string $search The name or the country name of the team &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to manches)
     * @param  string $country The country name of the team (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2019, 2020, 2021 ... (optional)
     * @param  float $id The id of the team (optional)
     * @param  string $name The name of the team (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchTeamAsyncWithHttpInfo($league = null, $search = 'manches', $country = null, $season = null, $id = null, $name = null)
    {
        $returnType = '';
        $request = $this->v3SearchTeamRequest($league, $search, $country, $season, $id, $name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3SearchTeam'
     *
     * @param  float $league The id of the league (optional)
     * @param  string $search The name or the country name of the team &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to manches)
     * @param  string $country The country name of the team (optional)
     * @param  float $season The season of the league &#x60;4 characters&#x60; Like 2019, 2020, 2021 ... (optional)
     * @param  float $id The id of the team (optional)
     * @param  string $name The name of the team (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3SearchTeamRequest($league = null, $search = 'manches', $country = null, $season = null, $id = null, $name = null)
    {

        $resourcePath = '/v3/teams';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($league !== null) {
            $queryParams['league'] = ObjectSerializer::toQueryValue($league, null);
        }
        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }
        // query params
        if ($country !== null) {
            $queryParams['country'] = ObjectSerializer::toQueryValue($country, null);
        }
        // query params
        if ($season !== null) {
            $queryParams['season'] = ObjectSerializer::toQueryValue($season, null);
        }
        // query params
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id, null);
        }
        // query params
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v3SearchVenue
     *
     * @param  string $city The city of the venue (optional)
     * @param  string $country The country name of the venue (optional)
     * @param  string $name The name of the venue (optional)
     * @param  float $id The id of the venue (optional)
     * @param  string $search The name, city or the country of the venue &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to old tr)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v3SearchVenue($city = null, $country = null, $name = null, $id = null, $search = 'old tr')
    {
        $this->v3SearchVenueWithHttpInfo($city, $country, $name, $id, $search);
    }

    /**
     * Operation v3SearchVenueWithHttpInfo
     *
     * @param  string $city The city of the venue (optional)
     * @param  string $country The country name of the venue (optional)
     * @param  string $name The name of the venue (optional)
     * @param  float $id The id of the venue (optional)
     * @param  string $search The name, city or the country of the venue &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to old tr)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v3SearchVenueWithHttpInfo($city = null, $country = null, $name = null, $id = null, $search = 'old tr')
    {
        $returnType = '';
        $request = $this->v3SearchVenueRequest($city, $country, $name, $id, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v3SearchVenueAsync
     *
     * 
     *
     * @param  string $city The city of the venue (optional)
     * @param  string $country The country name of the venue (optional)
     * @param  string $name The name of the venue (optional)
     * @param  float $id The id of the venue (optional)
     * @param  string $search The name, city or the country of the venue &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to old tr)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchVenueAsync($city = null, $country = null, $name = null, $id = null, $search = 'old tr')
    {
        return $this->v3SearchVenueAsyncWithHttpInfo($city, $country, $name, $id, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v3SearchVenueAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $city The city of the venue (optional)
     * @param  string $country The country name of the venue (optional)
     * @param  string $name The name of the venue (optional)
     * @param  float $id The id of the venue (optional)
     * @param  string $search The name, city or the country of the venue &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to old tr)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v3SearchVenueAsyncWithHttpInfo($city = null, $country = null, $name = null, $id = null, $search = 'old tr')
    {
        $returnType = '';
        $request = $this->v3SearchVenueRequest($city, $country, $name, $id, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v3SearchVenue'
     *
     * @param  string $city The city of the venue (optional)
     * @param  string $country The country name of the venue (optional)
     * @param  string $name The name of the venue (optional)
     * @param  float $id The id of the venue (optional)
     * @param  string $search The name, city or the country of the venue &#x60;&gt;&#x3D; 3 characters&#x60; (optional, default to old tr)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v3SearchVenueRequest($city = null, $country = null, $name = null, $id = null, $search = 'old tr')
    {

        $resourcePath = '/v3/venues';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($city !== null) {
            $queryParams['city'] = ObjectSerializer::toQueryValue($city, null);
        }
        // query params
        if ($country !== null) {
            $queryParams['country'] = ObjectSerializer::toQueryValue($country, null);
        }
        // query params
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name, null);
        }
        // query params
        if ($id !== null) {
            $queryParams['id'] = ObjectSerializer::toQueryValue($id, null);
        }
        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
